---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
data:
  CLUSTER_ID: 3a4d4d90-38b1-4b85-ad8a-48f7948a6c6b
  MANAGEMENT_NAMESPACE: kyma-system
  RELEASE_NAMESPACE: kyma-system
  ALLOW_CLUSTER_ACCESS: "true"
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: kyma-system
